### PR TITLE
V4 dev

### PR DESCRIPTION
**Pull request by Scientific-Guy**
Try to import this in repl.it and test it because episodes and shows is broken i guess

### CODE REVIEW

**Comment by GithubBoat** [comment]
@Scientific-Guy, Hey thanks for submitting this Pull Request, please wait while a collaborator reviews your PR

**Review by abh80 — APPROVED** [review]
looks good

**Comment by GithubBoat** [comment]
@Scientific-Guy, Everything looks good here, Great Job 
 I am ready to merge this PR on your behalf if you want so to happen please post a comment saying 
 > ready to merge

**Comment by Scientific-Guy** [comment]
ready to merge

**Comment by abh80** [comment]
ready to merge

**Pull request merged**
