### PR TITLE
Added playlist class with 2 functions

### PR DESCRIPTION
**Pull request by abh80**
- [x] Tested and working
- [x] Formatted using auto pep8
# The PR adds a Playlist class with 2 functions 

Thank You

### CODE REVIEW

**Comment by Scientific-Guy** [comment]
Useful Feature and good quality of codes
You can merge it

**Review by Scientific-Guy — APPROVED** [review]

**Comment by abh80** [comment]
ok thx

**Comment by abh80** [comment]
ready to merge

**Comment by abh80** [comment]
ready to merge

**Pull request merged**
